# Spring Properties
spring:
  application:
     name: publisher-service
  h2:
     console:
        enabled: true
        path: /h2
  datasource:
      url: jdbc:h2:file:~/dhis2-sync-client
      username: admin
      password: admin
      driver-class-name: org.h2.Driver
  activemq:
        broker-url: tcp://localhost:61616
        user: admin
        password: admin
  jpa:
      hibernate:
        ddl-auto: update



# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

dhis2:
  apiEndPoint: http://dhis.pgim.cmb.ac.lk/nss/api/
  username: chathura
  password: Chathura123
  config: config.json
  deliveryReportQueue: DNMS_event_delivery_reports