# Spring properties
spring:
  application:
     name: acceptor-service

# Discovery Server Access
eureka:
  instance:
    instance-id: ${random.value}
    hostname: localhost
    metadataMap:
          instanceId: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2223   # HTTP (Tomcat) port