# Spring Properties
spring:
  application:
     name: publisher-service
  h2:
     console:
        enabled: true
        path: /h2
  datasource:
      url: jdbc:h2:file:~/dhis2-sync-client
      username: admin
      password: admin
      driver-class-name: org.h2.Driver
  activemq:
        broker-url: tcp://localhost:61616
        user: admin
        password: admin
  jpa:
      hibernate:
        ddl-auto: update

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

dhis2:
  apiEndPoint: http://lankanets.info:8080/nss/api/
  username: dnms_sync
  password: DNMSSYNC1.
  config: config.json