# Spring properties
spring:
  application:
     name: acceptor-service
  activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin
  datasource:
      url: jdbc:mysql://localhost:3306/sync_server?autoReconnect=true&useSSL=false
      username: root
      password:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        max-await: 10000
        max-active: 200
        test-on-borrow: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true

# HTTP Server
server:
  port: 2223   # HTTP (Tomcat) port

config:
  max-event-handlers: 25000