# Spring properties
spring:
  application:
     name: acceptor-service
  h2:
       console:
          enabled: true
          path: /h2
  activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin
  datasource:
        url: jdbc:h2:file:~/dhis2-sync-server
        username: admin
        password: admin
        driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update


# Discovery Server Access
eureka:
  instance:
    instance-id: ${random.value}
    hostname: localhost
    metadataMap:
          instanceId: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2223   # HTTP (Tomcat) port